name: Deploy Prod Demo
on:
  push:
    branches:
      - master
jobs:
  build:
    name: Deployment Demo
    runs-on: ubuntu-latest
    steps:
      - name: SSH Remote
        uses: fifsky/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          user: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PASSWORD }}
          command: cd /var/www/html && git pull origin
